services:
  gaitanalyzer:
    image: abishekmuthian/gaitanalyzer:latest
    container_name: gaitanalyzer
    network_mode: "host"
    volumes:
      - ${PWD}/input_videos:/app/input_videos
      - ${PWD}/output_videos:/app/output_videos
    restart: unless-stopped
  ollama:
    image: ollama/ollama
    container_name: ollama
    privileged: true
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
volumes:
  ollama:
